"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.warningString = void 0;
exports.warningString = `// -------------------------------------
// WARNING
// THIS FILE IS AUTOGENERATED BY PRISMERGE
// DO NOT MANUALLY EDIT THIS FILE!
// -------------------------------------

`;
//# sourceMappingURL=warning.js.map