import { DMMF } from '@prisma/generator-helper'
import { GeneratorSettings } from '../interfaces/generator.interface';

export const generateEnum = ({ name, values }: DMMF.DatamodelEnum, settings: GeneratorSettings) => {
  const enumValues = values.map(({ name }) => `${name}="${name}"`).join(',\n');

  return `\n${settings.AutoGeneratedWarningText}\n\nenum ${name} { \n${enumValues}\n }`;
}

