import { DMMF } from '@prisma/generator-helper'
import { NestGeneratorSettings } from '../nest_settings.interface';

export const generateEnum = ({ name, values }: DMMF.DatamodelEnum, settings: NestGeneratorSettings) => {
  const enumValues = values.map(({ name }) => `${name}="${name}"`).join(',\n');

  return `\n${settings.AutoGeneratedWarningText}\n\nenum ${name} { \n${enumValues}\n }`;
}

