import { GeneratorSettings } from '../interfaces/generator.interface';
import { DMMF } from '@prisma/generator-helper';
import {
    crudRelationFieldStub,
    crudServiceStub,
    crudServiceStubWithExceptions,
    idMethods_neverThrow
} from '../stubs/crud.service.stub';
import * as path from 'path';
import { promises as fs } from 'fs';
import { NameGenerator } from '../nameGenerator';
import { FieldNameAndType, PrismaHelper, StringFns } from '@shared';

export class ServiceGenerator {

    private prismaHelper: PrismaHelper;

    constructor(
        private settings: GeneratorSettings,
        private model: DMMF.Model
    ) {
        this.prismaHelper = PrismaHelper.getInstance();
    }

    public async generateContent() {
        let nameGen = NameGenerator.singleton;
        let code: string;

        if (this.settings?.CRUDAddExceptions) {
            code = crudServiceStubWithExceptions;
            /*  content = content.replace(
                 /#{getMethod_neverThrow}/g,
                 this.prismaHelper.modelContainsObjectReference(this.model) ? getWithInclude_neverThrow: get_neverThrow); */
        } else {
            code = crudServiceStub;
        }
        code = code.replace(/#{AutoGeneratedWarningText}/g, this.settings.AutoGeneratedWarningText);
        if (this.settings.CRUDStubFile) {
            const stubFullPath = path.join(this.settings.schemaPath, this.settings.CRUDStubFile);
            console.log(`Loading Stubs from ${stubFullPath}`);

            const customStub = await fs.readFile(stubFullPath, { encoding: 'utf-8' });
            code = customStub.toString();
        }

        code = code.replace(/#{PrismaServiceImportPath}/g, this.settings.PrismaServiceImportPath)

       /*  const idFieldAndType = this.prismaHelper.getIdFieldNameAndType(this.model);

        // if the model has a unique ID field we insert '...byId' methods:
        if (idFieldAndType) {
            content = content.replace(/#{byIdMethods}/g, idMethods_neverThrow);
            content = this.replaceIdMethodTags(content, idFieldAndType);
        } else {
            content = content.replace(/#{byIdMethods}/g, '');
        } */

        
        
        code = code.replace(/#{byIdMethods}/g, this.addIdFieldMethods());

        code = code.replace(/#{relationFieldMethods}/g, this.addReferenceFieldMethods());
        code = code.replace(/#{RelatedFieldTypesImport}/g, this.addReferenceFieldImports());

        code = code.replace(/#{CrudServiceClassName}/g, nameGen.getClassName(this.model, 'service'));
        code = code.replace(/#{Model}/g, this.model.name);
        code = code.replace(/#{MODEL}/g, this.model.name.toUpperCase());
        code = code.replace(/#{model}/g, this.model.name.toLowerCase());
        code = code.replace(/#{moDel}/g, StringFns.decapitalize(this.model.name));
        return code;
    }

    addReferenceFieldMethods() {
        let code = '';
        const referenceFields = this.prismaHelper.getReferenceFields(this.model);
        referenceFields.forEach(field => {
            let stub = crudRelationFieldStub;
            stub = stub.replace(/#{RelationMethodReturnType}/g, field.isList ? `${field.type}[]` : field.type);
            stub = stub.replace(/#{RelationFieldType}/g, field.type);
            stub = stub.replace(/#{RelationFieldName}/g, field.name);
            stub = stub.replace(/#{RelationFieldNameCapitalized}/g, StringFns.capitalize(field.name));
            code += stub;
        });
        return code;
    }

    addReferenceFieldImports() {
        let content = '';
        const referenceFields = this.prismaHelper.getUniqueReferenceFields(this.model);
        referenceFields.forEach((fieldNameAndType) => content += `, ${fieldNameAndType.type}`);
        return content;
    }

    addIdFieldMethods() {
        let content = '';
        const idField = this.prismaHelper.getIdFieldNameAndType(this.model);
        if (idField) {
            content = idMethods_neverThrow;
            content = this.replaceIdMethodTags(content, idField);
        }
        return content;
    }

    replaceIdMethodTags(content: string, field: FieldNameAndType) {
        content = content.replace(/#{idName}/g, field.name);
        content = content.replace(/#{idType}/g, field.type);
        content = content.replace(/#{uniqueInputType}/g, `Prisma.${this.model.name}WhereUniqueInput`);
        return content;
    }
}



/*  let compoundkey = PrismaHelper.getInstance().getUniqueInputPropertyName(this.model);
            let compoundType = PrismaHelper.getInstance().getUniqueInputType(this.model);
            let prismaCompoundInputType = `Prisma.${this.model.name}${compoundType}CompoundUniqueInput`;
 
            crudServiceContent = crudServiceContent.replace(
                /#{uniqueInputType}/g,
                prismaCompoundInputType
            );
 */
/* crudServiceContent = crudServiceContent.replace(
    /#{uniqueKeyAndVal}/g,
    `{${compoundkey}: uniqueProps}`
); */