import { DMMF, GeneratorOptions } from "@prisma/generator-helper";
import { PrismaHelper, StringFns } from "@shared";
import { DartGeneratorSettings } from "../dart_settings.interface";
import { dartRecursiveListUpsert, dartStoreClassIncludeStub, dartStoreEndpoint, dartStoreEndpointAll, dartStoreEndpointAllName, dartStoreEndpointMany, dartStoreEndpointManyName, dartStoreEndpointName, dartStoreGetAll$, dartStoreGetByPropertyVal, dartStoreGetByPropertyVal$, dartStoreGetManyByPropertyVal, dartStoreGetManyByPropertyVal$, dartStoreGetRelatedModels, dartStoreGetRelatedModels$, dartStoreGetRelatedModelsWithId, dartStoreGetRelatedModelsWithId$, dartStoreGetVal, dartStoreIncludesConstructor, dartStoreIncludesEmptyConstructor, dartStoreRecursiveUpsert, dartStoreRecursiveUpsertForField, dartStoreRecursiveUpsertForListField, dartStoreStub } from "../stubs/store.stub";
import { DartGenerator } from "./dart.generator";


export class DartStoreGenerator {

    private prismaHelper: PrismaHelper;
    private dartGenerator: DartGenerator;

    constructor(private settings: DartGeneratorSettings, private model: DMMF.Model, private options: GeneratorOptions) {
        this.prismaHelper = PrismaHelper.getInstance();
        this.dartGenerator = new DartGenerator(settings, model);
    }

    generateContent() {

        let content = dartStoreStub;
        content = content.replace(/#{ModelsIdDartType}/g, this.prismaHelper.getIdFieldNameAndType(this.model, 'dart')?.type ?? 'null');
        content = content.replace(/#{AutoGeneratedWarningText}/g, this.settings.AutoGeneratedWarningText);
        content = content.replace(/#{Model}/g, this.model.name);

        const getValMethods: string[] = [];
        const getUniqueByPropertyVal: string[] = [];
        // const getPropToValueFunction: string[] = [];
        const getByPropertyVal: string[] = [];
        const GetRelatedModels: string[] = [];
        const GetRelatedModelsWithId: string[] = [];
        const getUniqueByPropertyVal$: string[] = [];
        const getByPropertyVal$: string[] = [];
        const endpoints: string[] = [];
        const GetRelatedModels$: string[] = [];
        const GetRelatedModelsWithId$: string[] = [];
        const modelFields: DMMF.Field[] = [];
        const includesConstructor: string[] = [];

        endpoints.push(this.generateEndpointAll());

        for (const field of this.model.fields) {
            if (field.kind === 'object') {
                modelFields.push(field);
                includesConstructor.push(this.generateIncludesConstructor(field));
                const relationFromFields = field.relationFromFields;
                
                if (relationFromFields != null && relationFromFields?.length > 0) {
                    const relatedFieldName = relationFromFields[0];
                    // const relationToField = this.prismaHelper.getRelationToFieldName(field, this.options) ?? '';
                    const relationToField = field.relationToFields?.[0] ?? '';
                    GetRelatedModelsWithId$.push(this.generateGetRelatedModelsWithId$(field, relatedFieldName, relationToField));
                    GetRelatedModelsWithId.push(this.generateGetRelatedModelsWithId(field, relatedFieldName));
                } /* else if (relationFromFields != null && relationFromFields.length === 0) {

                } */ else {
                    const relatedModelStore = `${field.type}Store`;
                    GetRelatedModels$.push(this.generateGetRelatedModels$(field, relatedModelStore));
                    GetRelatedModels.push(this.generateGetRelatedModels(field, relatedModelStore));
                }
            } else {
                getValMethods.push(this.generateGetValMethod(field));
                // getPropToValueFunction.push(this.generatePropertyToValFunction(field));
                if (field.isUnique || field.isId) {
                    getUniqueByPropertyVal$.push(this.generateGetByPropertyVal$(field));
                    if (!field.isId) {
                        getUniqueByPropertyVal.push(this.generateGetByPropertyVal(field));
                    }
                    endpoints.push(this.generateEndpoint(field));
                } else {
                    getByPropertyVal$.push(this.generateGetManyByPropertyVal$(field));
                    getByPropertyVal.push(this.generateGetManyByPropertyVal(field));
                    endpoints.push(this.generateEndpointMany(field));
                }
            }
        }

        content = content.replace(/#{GetAll\$}/g, this.generateGetAll$());
        content = content.replace(/#{GetValMethods}/g, getValMethods.join('\n\n\t'));
        content = content.replace(/#{GetByPropertyVal}/g, getUniqueByPropertyVal.join('\n\n\t'));
        // content = content.replace(/#{GetPropertyValueFunctions}/g, getPropToValueFunction.join('\n\n\t'));
        content = content.replace(/#{GetManyByPropertyVal}/g, getByPropertyVal.join('\n\n\t'));
        content = content.replace(/#{GetRelatedModelsWithId}/g, GetRelatedModelsWithId.join('\n\n\t'));
        content = content.replace(/#{GetRelatedModels}/g, GetRelatedModels.join('\n\n\t'));
        content = content.replace(/#{GetByPropertyVal\$}/g, getUniqueByPropertyVal$.join('\n\n\t'));
        content = content.replace(/#{GetManyByPropertyVal\$}/g, getByPropertyVal$.join('\n\n\t'));
        content = content.replace(/#{GetRelatedModelsWithId\$}/g, GetRelatedModelsWithId$.join('\n\n\t'));
        content = content.replace(/#{GetRelatedModels\$}/g, GetRelatedModels$.join('\n\n\t'));
        content = content.replace(/#{RecursiveUpsertsPlaceHolder}/g, this.generateRecursiveUpserts(modelFields));
        content = content.replace(/#{RecursiveListUpsertsPlaceHolder}/g, this.generateRecursiveListUpserts());
        content = content.replace(/#{Endpoints}/g, endpoints.join(',\n\t'));
        if (includesConstructor.length === 0) {
            includesConstructor.push(this.replaceAllVariables(dartStoreIncludesEmptyConstructor));
        }
        let classIncludeContent = this.replaceAllVariables(dartStoreClassIncludeStub);
        classIncludeContent = classIncludeContent.replace(/#{IncludeConstructors}/g, includesConstructor.join('\n\n\t'));
        content = content.replace(/#{ClassInclude}/g, classIncludeContent);
        /* } else {
            content = content.replace(/#{ClassInclude}/g, '');
        } */
        return content;
    }
    generateIncludesConstructor(field: DMMF.Field): string {
        let content = dartStoreIncludesConstructor;
        return this.replaceAllVariables(content, field);
    }

    generateGetValMethod(field: DMMF.Field) {
        let content = dartStoreGetVal;
        return this.replaceAllVariables(content, field);
    }

    /* generatePropertyToValFunction(field: DMMF.Field) {
        let content = getPropertyValueFunctionStub;
        return this.replaceAllVariables(content, field);
    } */

    generateGetAll$() {
        let content = dartStoreGetAll$;
        content = content.replace(/#{EndPointAllName}/g, dartStoreEndpointAllName);
        return this.replaceAllVariables(content);
    }

    generateGetByPropertyVal(field: DMMF.Field) {
        let content = dartStoreGetByPropertyVal;
        return this.replaceAllVariables(content, field);
    }

    generateGetManyByPropertyVal(field: DMMF.Field) {
        let content = dartStoreGetManyByPropertyVal;
        return this.replaceAllVariables(content, field);
    }

    generateGetRelatedModelsWithId(field: DMMF.Field, relationFromField: string) {
        let content = dartStoreGetRelatedModelsWithId;
        content = content.replace(/#{relationFromField}/g, relationFromField);
        // content = content.replace(/#{GetIncludingType}/g, `${field.type}`);
        content = content.replace(/#{StreamReturnType}/g, `${field.type}?`);
        return this.replaceAllVariables(content, field);
    }

    generateGetRelatedModels(field: DMMF.Field, relatedModelStore: string) {
        const relationToFieldName = PrismaHelper.getInstance().getRelationToFieldName(field, this.options) ?? '';
        const relationToFieldNameCapitalized = StringFns.capitalize(relationToFieldName);
        let content = dartStoreGetRelatedModels;
        content = content.replace(/#{RelatedModelStore}/g, relatedModelStore);
        // content = content.replace(/#{GetIncludingType}/g, `${field.type}`);
        content = content.replace(/#{relationToFieldName}/g, relationToFieldName);
        content = content.replace(/#{RelationToFieldName}/g, relationToFieldNameCapitalized);
        if (field.isList) {
            content = content.replace(/#{StreamReturnType}/g, `List<${field.type}>`);
            content = content.replace(/#{setRefModelFunction}/g, 'setIncludedReferencesForList');
        } else {
            content = content.replace(/#{StreamReturnType}/g, `${field.type}?`);
            content = content.replace(/#{setRefModelFunction}/g, 'setIncludedReferences');
        }
        return this.replaceAllVariables(content, field);
    }

    generateRecursiveUpserts(fields: DMMF.Field[]) {
        let content = dartStoreRecursiveUpsert;
        content = this.replaceAllVariables(content);
        let recursiveUpserts = '';
        for (const field of fields) {
            recursiveUpserts += this.generateRecursiveUpsertForField(field);
        }
        content = content.replace(/#{RecursiveUpsertsForFields}/g, recursiveUpserts);
        content = content.replace(/#{UpdateStoresRecursiveDepth_SETTING}/g, this.settings.UpdateStoresDefaultRecursiveDepth.toString());
        return content;
    }

    generateRecursiveUpsertForField(field: DMMF.Field) {
        let content = field.isList ? dartStoreRecursiveUpsertForListField : dartStoreRecursiveUpsertForField;
        content = content.replace(/#{FieldType}/g, field.type);
        return this.replaceAllVariables(content, field);
    }

    generateRecursiveListUpserts() {
        let content = dartRecursiveListUpsert;
        content = content.replace(/#{UpdateStoresRecursiveDepth_SETTING}/g, this.settings.UpdateStoresDefaultRecursiveDepth.toString());
        return this.replaceAllVariables(content);
    }

    generateGetByPropertyVal$(field: DMMF.Field) {
        let content = dartStoreGetByPropertyVal$;
        content = content.replace(/#{EndPointName}/g, this.generateEndpointName(true));
        return this.replaceAllVariables(content, field);
    }

    generateGetManyByPropertyVal$(field: DMMF.Field) {
        let content = dartStoreGetManyByPropertyVal$;
        content = content.replace(/#{EndPointManyName}/g, this.generateEndpointName(false));
        return this.replaceAllVariables(content, field);
    }


    generateGetRelatedModelsWithId$(field: DMMF.Field, relationFromField: string, relationToField: string) {
        let content = dartStoreGetRelatedModelsWithId$;
        content = content.replace(/#{relationFromField}/g, relationFromField);
        content = content.replace(/#{StreamReturnType}/g, `${field.type}?`);
        // const fieldObject = this.prismaHelper.getModel(field.type);
        // const getByIdInRelatedModel$ = this.prismaHelper.getIdFieldNameAndType(relationToField, 'dart')?.name ?? '';
        content = content.replace(/#{getByIdInRelatedModel\$}/g, `getBy${StringFns.capitalize(relationToField)}$`);
        // content = content.replace(/#{GetIncludingType}/g, `${field.type}`);
        
        /* if (field.isList) {
            content = content.replace(/#{getIncluding\$}/g, 'getManyIncluding$');
        } else {
            content = content.replace(/#{getIncluding\$}/g, 'getIncluding$');
        } */
        return this.replaceAllVariables(content, field);
    }

    generateGetRelatedModels$(field: DMMF.Field, relatedModelStore: string) {
        let relationToFieldName = StringFns.capitalize(PrismaHelper.getInstance().getRelationToFieldName(field, this.options) ?? '');
        let content = dartStoreGetRelatedModels$;
        content = content.replace(/#{RelatedModelStore}/g, relatedModelStore);
        // content = content.replace(/#{GetIncludingType}/g, `${field.type}`);
        content = content.replace(/#{RelationToFieldName}/g, relationToFieldName);
        if (field.isList) {
            content = content.replace(/#{StreamReturnType}/g, `List<${field.type}>`);
            // content = content.replace(/#{getIncluding\$}/g, 'getManyIncluding$');
        } else {
            content = content.replace(/#{StreamReturnType}/g, `${field.type}?`);
            // content = content.replace(/#{getIncluding\$}/g, 'getIncluding$');
        }

        return this.replaceAllVariables(content, field);
    }


    generateEndpoint(field: DMMF.Field) {
        let content = dartStoreEndpoint;
        content = content.replace(/#{EndPointName}/g, this.generateEndpointName(true));
        return this.replaceAllVariables(content, field);
    }

    generateEndpointMany(field: DMMF.Field) {
        let content = dartStoreEndpointMany;
        content = content.replace(/#{EndPointManyName}/g, this.generateEndpointName(false));
        return this.replaceAllVariables(content, field);
    }

    generateEndpointAll() {
        let content = dartStoreEndpointAll;
        content = content.replace(/#{EndPointAllName}/g, dartStoreEndpointAllName);
        return this.replaceAllVariables(content);
    }

    replaceAllVariables(content: string, field?: DMMF.Field) {
        return this.dartGenerator.replaceAllVariables(content, field);
        /* if (field) {
            content = content.replace(/#{FieldType}/g, this.dartGenerator.getDartType(field));
            content = content.replace(/#{IncludeType}/g, `List<${field.type}Include>?`);
            content = content.replace(/#{fieldName}/g, field.name);
            content = content.replace(/#{FieldName}/g, StringFns.capitalize(field.name));
        }
        content = content.replace(/#{Nullable}/g, '?');
        // content = content.replace(/#{model}/g, StringFns.decapitalize(this.model.name));
        content = content.replace(/#{moDel}/g, StringFns.decapitalize(this.model.name));
        content = content.replace(/#{Model}/g, this.model.name);
        return content; */
    }

    generateEndpointName(returnsSingleRecord: boolean) {
        return returnsSingleRecord ? dartStoreEndpointName : dartStoreEndpointManyName;
    }
}