import { DMMF } from '@prisma/generator-helper'
import { dartEnumStub } from '../stubs/dart.stub';

export const generateDartEnum = ({ name, values }: DMMF.DatamodelEnum, autoGenText: string) => {
    const enumValues = values.map(({ name }) => name).join(',\n\t');

    // return `${autoGenText}\nenum ${name} {\n\t${enumValues}\n}`;

    let enumStub = dartEnumStub;
    enumStub = enumStub.replace(/#{AutoGeneratedWarningText}/g, autoGenText);
    enumStub = enumStub.replace(/#{ModelName}/g, name);
    enumStub = enumStub.replace(/#{EnumValues}/g, enumValues);
    return enumStub;
}