export const moduleStub = `
#{AutoGeneratedWarningText}

import { Module } from '@nestjs/common';
import { #{ServiceName} } from './#{ServiceFileName}';
import { #{ControllerName} } from './#{ControllerFileName}';
import { #{PrismaModuleName} } from '#{PrismaModuleImportPath}';

@Module({
  controllers: [#{ControllerName}],
  providers: [#{ServiceName}],
  imports: [#{PrismaModuleName}]
})
export class #{Model}Module {}`;