export interface GeneratorSettings {
    strict?: boolean;
    dryRun?: boolean;
    AutoGeneratedWarningText: string;
    prefix?: string;
    schemaPath: string;
    GenerateServices?: boolean; 
    // GenerateInputs?: boolean;
    GenerateControllers?: boolean;
    // GenerateInputSwagger?: boolean;
    GenerateModule?: boolean;

    InputExportPath: string;
    InputSuffix: string;
    InputValidatorPackage: string;
    InputParentClass?: string;
    InputParentClassPath?: string;
    InputCreatePrefix: string;
    InputUpdatePrefix: string;
    CRUDStubFile?: string;
    CRUDAddExceptions?: boolean;
    PrismaServiceImportPath: string;

    EnumPath: string;

    GuardClass?: String;
    GuardImportPath?: String;

    
    PrismaModuleName?: string;
    PrismaModuleImportPath?: string;
}
