export const controllerStub = `
#{AutoGeneratedWarningText}

import { Controller, Get, Post, Body, Patch, Param, Delete, UseGuards } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { #{ServiceName} } from './#{CrudServiceFileName}';
#{ImportGuardClass}

@Controller('#{model}')
export class #{ControllerClassName} {
  constructor(private readonly service: #{ServiceName}) {}

#{create}

#{getAll}

#{getFilteredPage}

#{getUnique}
 
#{update}
  
#{getById}

#{updateById}

#{deleteById}

#{referenceField}
  
}`;



export const controllerCreateStub = `
#{GuardDecorator}
  @Post('create')
  create(@Body() #{moDel}CreateInput: Prisma.#{Model}CreateInput) {
    return this.service.create(#{moDel}CreateInput);
  }
`;

export const controllerGetAllStub = `
#{GuardDecorator}
@Get()
getAll() {
  return this.service.getAll();
}
`;

export const controllergetFilteredPageStub = `
#{GuardDecorator}
  @Post('getFilteredPage')
  getFilteredPage(@Body() data: Prisma.#{Model}FindManyArgs) {
    return this.service.getFilteredPage(data);
  }
`;

export const controllerGetUniqueStub = `
#{GuardDecorator}
@Post('unique')
getUnique(@Body() body: Prisma.#{Model}FindUniqueOrThrowArgs) {
  return this.service.getUnique(body);
}
`;

export const controllerUpdateStub = `
#{GuardDecorator}
  @Post('update')
  update(@Body() body: {where: Prisma.#{Model}WhereUniqueInput; data: Prisma.#{Model}UpdateInput}) {
    return this.service.update({where: body.where, data: body.data});
  }
`;

export const controllerGetByIdStub = `
#{GuardDecorator}
  @Get(':id')
  getById(@Param('id') id: string) {
    return this.service.getById(#{convertToInt}id);
  }
`;

export const controllerUpdateByIdStub = `
#{GuardDecorator}
    @Patch(':id')
    updateById (@Param('id') id: string, @Body() data: Prisma.#{Model}UpdateInput) {
        return this.service.updateById(#{convertToInt}id, data);
    }
`;

export const controllerDeleteByIdStub = `
#{GuardDecorator}
    @Delete(':id')
    deleteById(@Param('id') id: string) {
        return this.service.deleteById(#{convertToInt}id);
    }
`;

export const controllerReferenceFieldStub = `
#{GuardDecorator}
  @Post('#{RelationFieldName}')
  get#{RelationFieldNameCapitalized}(@Body() body: Prisma.#{Model}WhereUniqueInput) {
    return this.service.get#{RelationFieldNameCapitalized}(body);
  }
`;

export const controllerMethodStubs = {
    create: controllerCreateStub,
    getAll: controllerGetAllStub,
    getFilteredPage: controllergetFilteredPageStub,
    getUnique: controllerGetUniqueStub,
    update: controllerUpdateStub,
    getById: controllerGetByIdStub,
    updateById: controllerUpdateByIdStub,
    deleteById: controllerDeleteByIdStub,
    referenceField: controllerReferenceFieldStub
}

export const controllerMethodNames = Object.keys(controllerMethodStubs);

/* export const controllerIdMethodsStub = `
#{GuardDecorator}
  @Get(':id')
  getById(@Param('id') id: string) {
    return this.service.getById(#{convertToInt}id);
  }

  #{GuardDecorator}
  @Patch(':id')
  updateById (@Param('id') id: string, @Body() data: Prisma.#{Model}UpdateInput) {
    return this.service.updateById(#{convertToInt}id, data);
  }

  #{GuardDecorator}
  @Delete(':id')
  deleteById(@Param('id') id: string) {
    return this.service.deleteById(#{convertToInt}id);
  }` */