export const moduleStub = `
#{AutoGeneratedWarningText}

import { Module } from '@nestjs/common';
import { #{ServiceName} } from './#{ServiceFileName}';
import { #{PrismaModuleName} } from '#{PrismaModuleImportPath}';
#{ImportControllerClass}
@Module({
  controllers: [#{ControllerName}],
  providers: [#{ServiceName}],
  imports: [#{PrismaModuleName}]
})
export class #{ModuleName} {}`;

export const importControllerStub = `import { #{ControllerName} } from './#{ControllerFileName}';`;